# CMake generated Testfile for 
# Source directory: /home/ubuntu/VCNN/libsnark
# Build directory: /home/ubuntu/VCNN/libsnark/libsnark
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(common_routing_algorithms_test "/home/ubuntu/VCNN/libsnark/libsnark/common_routing_algorithms_test")
set_tests_properties(common_routing_algorithms_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;805;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib1_simple_test "/home/ubuntu/VCNN/libsnark/libsnark/gadgetlib1_simple_test")
set_tests_properties(gadgetlib1_simple_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;809;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib1_r1cs_ppzksnark_verifier_gadget_test "/home/ubuntu/VCNN/libsnark/libsnark/gadgetlib1_r1cs_ppzksnark_verifier_gadget_test")
set_tests_properties(gadgetlib1_r1cs_ppzksnark_verifier_gadget_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;813;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_adapters_test "/home/ubuntu/VCNN/libsnark/libsnark/gadgetlib2_adapters_test")
set_tests_properties(gadgetlib2_adapters_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;817;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_constraint_test "/home/ubuntu/VCNN/libsnark/libsnark/gadgetlib2_constraint_test")
set_tests_properties(gadgetlib2_constraint_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;821;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_gadget_test "/home/ubuntu/VCNN/libsnark/libsnark/gadgetlib2_gadget_test")
set_tests_properties(gadgetlib2_gadget_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;825;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_integration_test "/home/ubuntu/VCNN/libsnark/libsnark/gadgetlib2_integration_test")
set_tests_properties(gadgetlib2_integration_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;829;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_protoboard_test "/home/ubuntu/VCNN/libsnark/libsnark/gadgetlib2_protoboard_test")
set_tests_properties(gadgetlib2_protoboard_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;833;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_variable_test "/home/ubuntu/VCNN/libsnark/libsnark/gadgetlib2_variable_test")
set_tests_properties(gadgetlib2_variable_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;837;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(relations_qap_test "/home/ubuntu/VCNN/libsnark/libsnark/relations_qap_test")
set_tests_properties(relations_qap_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;841;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(relations_sap_test "/home/ubuntu/VCNN/libsnark/libsnark/relations_sap_test")
set_tests_properties(relations_sap_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;845;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(relations_ssp_test "/home/ubuntu/VCNN/libsnark/libsnark/relations_ssp_test")
set_tests_properties(relations_ssp_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;849;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_bacs_ppzksnark_test "/home/ubuntu/VCNN/libsnark/libsnark/zk_proof_systems_bacs_ppzksnark_test")
set_tests_properties(zk_proof_systems_bacs_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;853;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_r1cs_ppzksnark_test "/home/ubuntu/VCNN/libsnark/libsnark/zk_proof_systems_r1cs_ppzksnark_test")
set_tests_properties(zk_proof_systems_r1cs_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;857;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_r1cs_se_ppzksnark_test "/home/ubuntu/VCNN/libsnark/libsnark/zk_proof_systems_r1cs_se_ppzksnark_test")
set_tests_properties(zk_proof_systems_r1cs_se_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;861;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_r1cs_gg_ppzksnark_test "/home/ubuntu/VCNN/libsnark/libsnark/zk_proof_systems_r1cs_gg_ppzksnark_test")
set_tests_properties(zk_proof_systems_r1cs_gg_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;865;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_ram_ppzksnark_test "/home/ubuntu/VCNN/libsnark/libsnark/zk_proof_systems_ram_ppzksnark_test")
set_tests_properties(zk_proof_systems_ram_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;869;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_tbcs_ppzksnark_test "/home/ubuntu/VCNN/libsnark/libsnark/zk_proof_systems_tbcs_ppzksnark_test")
set_tests_properties(zk_proof_systems_tbcs_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;873;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_uscs_ppzksnark_test "/home/ubuntu/VCNN/libsnark/libsnark/zk_proof_systems_uscs_ppzksnark_test")
set_tests_properties(zk_proof_systems_uscs_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;877;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(test_knapsack_gadget "/home/ubuntu/VCNN/libsnark/libsnark/test_knapsack_gadget")
set_tests_properties(test_knapsack_gadget PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;881;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(test_merkle_tree_gadgets "/home/ubuntu/VCNN/libsnark/libsnark/test_merkle_tree_gadgets")
set_tests_properties(test_merkle_tree_gadgets PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;885;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(test_set_commitment_gadget "/home/ubuntu/VCNN/libsnark/libsnark/test_set_commitment_gadget")
set_tests_properties(test_set_commitment_gadget PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;889;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(test_sha256_gadget "/home/ubuntu/VCNN/libsnark/libsnark/test_sha256_gadget")
set_tests_properties(test_sha256_gadget PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;893;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_convol_snark "/home/ubuntu/VCNN/libsnark/libsnark/zk_proof_systems_convol_snark")
set_tests_properties(zk_proof_systems_convol_snark PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;897;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_convol_snark_test "/home/ubuntu/VCNN/libsnark/libsnark/zk_proof_systems_convol_snark_test")
set_tests_properties(zk_proof_systems_convol_snark_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;901;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_convol_snark_vcnn "/home/ubuntu/VCNN/libsnark/libsnark/zk_proof_systems_convol_snark_vcnn")
set_tests_properties(zk_proof_systems_convol_snark_vcnn PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;905;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
add_test(new_commit_vcnn "/home/ubuntu/VCNN/libsnark/libsnark/new_commit_vcnn")
set_tests_properties(new_commit_vcnn PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/VCNN/libsnark/CMakeLists.txt;909;add_test;/home/ubuntu/VCNN/libsnark/CMakeLists.txt;0;")
